package org.dragan;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;

public class MyList extends JFrame {
    private String data[][] = {
            {"101", "Amit", "670000"},
            {"102", "Jai", "780000"},
            {"101", "Sachin", "700000"}
    };
    private String column[] = {"ID", "Nom", "Genre"};
    private TableModel dataModel = new DefaultTableModel(data, column);

    private JPanel mainPanel;
    private JScrollPane tableScrollPane;
    private JTable personneTable;

    public MyList() {
        super("Examen");

        personneTable.setModel(dataModel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        tableScrollPane = new JScrollPane();
        tableScrollPane.setAutoscrolls(false);
        tableScrollPane.setName("");
        tableScrollPane.setOpaque(false);
        mainPanel.add(tableScrollPane, BorderLayout.CENTER);
        tableScrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Liste des utilisateurs", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        personneTable = new JTable();
        tableScrollPane.setViewportView(personneTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
